# Generated by Django 3.2.7 on 2021-10-18 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='descptions',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
