# Generated by Django 3.2.8 on 2021-10-19 12:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app1', '0012_auto_20211019_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutcontent',
            name='city',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='aboutcontent',
            name='designation',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='aboutcontent',
            name='education',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='aboutcontent',
            name='phone',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='aboutcontent',
            name='status',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='aboutcontent',
            name='website',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='countup',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='education',
            name='degree',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='education',
            name='inistitute',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='profesionalexperience',
            name='designation',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='profesionalexperience',
            name='inistitute',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='skill',
            name='bg',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='skill',
            name='percent',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='skill',
            name='value',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='summary',
            name='address',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='summary',
            name='phone',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='designation',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('descption', models.TextField()),
                ('icon', models.ImageField(upload_to='service-icon')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
