# Generated by Django 3.2.8 on 2021-10-19 12:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app1', '0013_auto_20211019_1806'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Service',
            new_name='ServicePart',
        ),
    ]
