# Generated by Django 3.2.8 on 2021-10-24 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_rename_service_servicepart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicepart',
            name='icon',
        ),
    ]
