# Generated by Django 3.2.8 on 2021-10-24 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_remove_servicepart_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepart',
            name='icon',
            field=models.ImageField(default=1, upload_to='service-icon'),
            preserve_default=False,
        ),
    ]
